//#created on: 30 oct. 2010
package lesson4

//#list any import classes here.
import droolscours.Account;
import java.util.List;

//#declare any global variables here


global droolscours.util.OutputDisplay showResults;

rule "start ruleflow group1"
    salience -500
	when
	then
		kcontext.getKieRuntime().getAgenda().getAgendaGroup("Group1").setFocus();
end

rule "Account group1 4"
    salience -500
	ruleflow-group "Group1"
	when
		Account(  )
	then 
		showResults.showText("Account in Group1");
		
end

rule "start ruleflow group2"
	ruleflow-group "Group1"
	when

	then
		kcontext.getKieRuntime().getAgenda().getAgendaGroup("Group2").setFocus();
end

rule "Account group2 4"
	ruleflow-group "Group2"
	when
		Account(  )
	then 
		showResults.showText("Account in Group2");
		
end

