
package rules

import cost.OrderLine;
import cost.LeftToDistribute;
import cost.Product;
import cost.Pallet;
import cost.CostCalculationRequest;
import cost.CalculatedElement;
import cost.HandlingCostElement;
import cost.TaxesCostElement;
import cost.TransportCostElement;
import cost.Step;
import cost.City;

import java.lang.Math;

rule "CalculateTotal"
ruleflow-group "total"
	when
	$c : CostCalculationRequest(  )
	$totalBoatTransport : Number( doubleValue > 100 )
             from accumulate( $s : Step(transportType ==Step.Ship_TransportType) &&
                              TransportCostElement(step ==$s, $value : amount  ),
                               sum($value))
	$totalTrainTransport : Number( doubleValue > 100 )
            from accumulate( $s : Step(transportType ==Step.train_TransportType) &&
                            TransportCostElement(step ==$s, $value : amount  ),
                             sum($value) )
	$totalTruckTransport : Number( doubleValue > 100 )
           from accumulate( $s : Step(transportType ==Step.truck_TransportType) &&
                            TransportCostElement(step ==$s, $value : amount  ),
                             sum($value) )
	
	
	
	$totalTransport : Number( doubleValue > 100 )
             from accumulate(  TransportCostElement( $value : amount  ),
                               sum($value) )
    $totalTaxes : Number( doubleValue > 100 )
             from accumulate(  TaxesCostElement( $value : amount  ),
                              sum($value))
     $totalHandling : Number( doubleValue > 100 )
             from accumulate(  HandlingCostElement( $value : amount  ),
                              sum($value) )
	then
		System.out.println("NumberOfPallets="+$c.getPallets().size());
		System.out.println("TotalShipTransport="+$totalBoatTransport);
		System.out.println("TotalTrainTransport="+$totalTrainTransport);
		System.out.println("TotalTruckTransport="+$totalTruckTransport);
		System.out.println("TotalTransport="+$totalTransport);
		System.out.println("TotalTaxes="+$totalTaxes);
		System.out.println("TotalHandling="+$totalHandling);
end;
