//#created on: 30 oct. 2010
package lesson4a

//#list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import droolscours.util.OutputDisplay;
//#declare any global variables here


global droolscours.util.OutputDisplay showResults;

rule "start ruleflow group1"
    salience -500
	when
	    Account(balance >= 1000)
	then
		kcontext.getKieRuntime().getAgenda().getAgendaGroup("Group1").setFocus();
end

rule "Account group1 4a"
	ruleflow-group "Group1"
	when
		Account(balance > 0  )
	then 
		showResults.showText("Account in Group1 > 1000 ");
		
end
rule "start ruleflow group2"
    salience -500
	when
	    Account(balance < 1000)
	then
		kcontext.getKieRuntime().getAgenda().getAgendaGroup("Group2").setFocus();
end

rule "Account group2 4a"
	ruleflow-group "Group2"
	when
		Account(  )
	then 
		showResults.showText("Account in Group2 < 1000");
		
end

