//#created on: 30 oct. 2010
package lesson4Classical

//#list any import classes here.
import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import droolscours.util.OutputDisplay;
import java.util.List;

//#declare any global variables here


global droolscours.util.OutputDisplay showResults;



rule "Account group1 4"
    salience -500
	ruleflow-group "Group1"
	when
		Account(  )
	then 
		showResults.showText("Account in Group1");
		
end



rule "Account group2 4"
	ruleflow-group "Group2"
	when
		Account(  )
	then 
		showResults.showText("Account in Group2");
		
end

